name: My First Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print message
      run: |
       echo "Hello"
       echo "GitHub Actions"
    - name: List files
      run: ls
    - name: Show OS
      run: uname -a
    - name: Step 1
      run: echo "Step 1"
    - name: Step 2
      run: echo "Step 2"
    - name: Step 3
      run: 
       echo "URMILA BHAURAO"
       echo date
      
      
