name: My First Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print message
      run: |
       echo "Hello"
       echo "GitHub Actions"
    - name: List files
      run: ls
